language: java


jdk:
  - oraclejdk8


script:
  - mvn clean package

after_success:
  - java -jar target/benchmarks.jar StatesVolatile -wi 5 -i 5 -t 4 -f 1
  - java -jar target/benchmarks.jar StatesNonVolatile -wi 5 -i 5 -t 4 -f 1